name: Deploy multicontainer app
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t andacaydin/client ./client
      - run: docker build -t andacaydin/nginx ./nginx
      - run: docker build -t andacaydin/server ./server
      - run: docker build -t andacaydin/worker ./worker          
 
      - run: docker push andacaydin/client
      - run: docker push andacaydin/nginx 
      - run: docker push andacaydin/server 
      - run: docker push andacaydin/worker      

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multidocker-application
          environment_name: ECS-environment
          existing_bucket_name: elasticbeanstalk-eu-north-1-265072780787
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          use_existing_version_if_available: true